source 'https://rubygems.org'
ruby '2.3.1'

gem 'rails', '4.2.4'

gem 'aasm', '3.4.0'
gem 'activerecord-postgis-adapter', '3.1.2'
gem 'aws-sdk', '2.6.12'
gem 'barby', '0.6.2'
gem 'bcrypt', '3.1.10'
gem 'cancancan', '~> 1.13'
gem 'chunky_png', '1.3.4'
gem 'crypt_keeper', '1.1.1'
gem 'eth', '0.4.4'
gem 'gcm', '0.1.0'
gem 'houston', '2.2.3'
gem 'jwt'
gem 'koala'
gem 'newrelic_rpm', '~> 3.12'
gem 'oj', '2.12.7'
gem 'paper_trail', '~> 4.0.0.beta'
gem 'pg', '~> 0.18'
gem 'possessive', '1.0.0'
gem 'provide-ruby', '0.24.0'
gem 'rabl', '0.11.6'
gem 'rack-cors', '0.4.0'
gem 'recaptcha', '1.1.0', require: 'recaptcha/rails'
gem 'responders', '~> 2.1'
gem 'resque', '1.25.2'
gem 'resque-pool', '0.6.0'
gem 'resque-scheduler', '4.0.0'
gem 'rolify', '4.0.0'
gem 'settingslogic', '~> 2.0.9'
gem 'shortener', '0.3.1'
gem 'stripe', '3.3.1'
gem 'stripe-rails', '1.1.1'
gem 'timezone', '0.5.0'
gem 'tzinfo-data'
gem 'twilio-ruby', '3.11.6'
gem 'typhoeus', '~> 1.3'
gem 'faye-websocket', '0.10.0'
gem 'websocket-rails', '0.7.0'
gem 'hiredis'
gem 'redis', '3.2.1', require: %w(redis redis/connection/hiredis)

group :production do
  gem 'unicorn', '~> 4.9'
  gem 'unicorn-worker-killer', '0.4.4'
end

group :development, :test do
  gem 'better_errors', '2.1.1'
  gem 'bullet', '5.0.0'
  gem 'factory_girl_rails', '~> 4.5'
  gem 'faker', '~> 1.4'
  gem 'pry', '~> 0.10'
  gem 'pry-highlight', '~> 0.1'
  gem 'pry-stack_explorer', '~> 0.4.9'
  gem 'rspec-rails', '~> 3.2'
end

group :test do
  gem 'database_cleaner', '~> 1.4'
  gem 'resque_spec', '~> 0.16'
  gem 'shoulda-matchers', '~> 2.8'
  gem 'simplecov', '~> 0.10'
  gem 'stripe-ruby-mock', :require => 'stripe_mock'
  gem 'timecop', '~> 0.7'
  gem 'vcr', '~> 2.9'
  gem 'webmock', '~> 1.20'
end
